### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by br4nnigan** [magento-research/magento-eslint#15]
When I install this locally in my project as stated:

`npm install @magento/eslint-config`

then I will get this folder structure:

`node_modules/@magento/eslint-config/index.js`
`node_modules/@magento/eslint-config/package.json`
`node_modules/@magento/eslint-config/README.md`

Nothing more. Of course all dependancies are missing when trying to use the config to lint (error complains about missing prettier).

When I go into the `node_modules/@magento/eslint-config` folder and do `npm install` the dependancies are installed into that folder. Trying to use the config to lint now for some reason gives a different error (can't find plugin eslint-plugin-jsx-a11y).

What gives?

**Comment by br4nnigan** [comment]
$ node -v
    v14.16.0
    $ npm -v
    6.14.11

**Comment by br4nnigan** [comment]
I could only solve this by manually adding the module dev-depandancies to my projects dev-depandancies

**Comment by sirugh** [comment]
What does the initial `npm install` output say? Any hints?

**Comment by br4nnigan** [comment]
Sorry I can't tell you, I'm done with Magento. I quit my job. Hooray!
